version: '3.3'

services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks: 
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    env_file: .env
    restart: on-failure

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    expose: 
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'User/login/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/User/login/data/mariadb'

networks:
  inception:
    # name: inception
    driver: bridge