version: '3.3'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    env_file: .env

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
