services:

  nginx:
  container_name: nginx
  image: nginx
  build:
  context: ./requirements/nginx
  dockerfile: Dockerfile
  ports:
  - "80:80"
  - "443:443"
  env_file:
  - .env

  mariadb:
  container_name: mariadb
  image: mariadb
  build:
  context: requirements/mariadb
  dockerfile: Dockerfile
  env_file:
  - .env
  volumes:
  - mariadb:/var/lib/mysql
  restart: unless-stopped
  expose:
  - "3306"
